// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULklhZvoBuYaMIW14OKHq_MIOaHiPxU0',
    appId: '1:986954955333:web:76febdfecb7311a0e2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    authDomain: 'senerity-3930a.firebaseapp.com',
    storageBucket: 'senerity-3930a.appspot.com',
    measurementId: 'G-FRP7MYTV5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Py0049cS2-GSylLoKW6ivILFvdz5CJ0',
    appId: '1:986954955333:android:7f85f21ff379bface2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    storageBucket: 'senerity-3930a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdkeREBffwuIOANOU5HYVTmNmksCXNz8',
    appId: '1:986954955333:ios:7589ae712be82042e2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    storageBucket: 'senerity-3930a.appspot.com',
    iosClientId: '986954955333-eq6foa7aj4q1pcgh2u9kpn42mc1u59or.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdkeREBffwuIOANOU5HYVTmNmksCXNz8',
    appId: '1:986954955333:ios:7589ae712be82042e2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    storageBucket: 'senerity-3930a.appspot.com',
    iosClientId: '986954955333-eq6foa7aj4q1pcgh2u9kpn42mc1u59or.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled5',
  );
}
